name: C/C++ Doxygen Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Doxygen Generation
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'Documentation/Doxyfile'
        
    - name: GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.Doxygen_Key }}
        publish_dir: ./public
        
