name: C/C++ Doxygen Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Doxygen Generation
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'Documentation/Doxyfile'
        
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: 'Documentation/'
      env:
        GITHUB_PAT: ${{ secrets.9a879bacdc64cec75507ac344892d9a6d3ca801e }}  
